services:
    desouk_online.real_estate:
        class: DesoukOnline\RealEstateBundle\Admin\RealEstateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "DesoukOnline", label: "Real Estate" , show_in_dashboard: true }
        arguments:
            - ~
            - DesoukOnline\RealEstateBundle\Entity\RealEstate
            - ~
    desouk_online.real_estate.area:
        class: DesoukOnline\RealEstateBundle\Admin\AreaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "DesoukOnline", label: "Areas" , show_in_dashboard: true }
        arguments:
            - ~
            - DesoukOnline\RealEstateBundle\Entity\Area
            - ~
    desouk_online.real_estate.image:
        class: DesoukOnline\RealEstateBundle\Admin\ImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "DesoukOnline", label: "Images" }
        arguments:
            - ~
            - DesoukOnline\RealEstateBundle\Entity\Image
            - ~