services:
    desouk_online.mall.config:
        class: DesoukOnline\MallBundle\Admin\MallConfigAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Mall", label: "Config" , show_in_dashboard: true }
        arguments:
            - ~
            - DesoukOnline\MallBundle\Entity\MallConfig
            - ~


    desouk_online.mall.vendor:
        class: DesoukOnline\MallBundle\Admin\VendorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Mall", label: "Vendors" , show_in_dashboard: true }
        arguments:
            - ~
            - DesoukOnline\MallBundle\Entity\Vendor
            - ~

    desouk_online.mall.category:
        class: DesoukOnline\MallBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Mall", label: "Categories" , show_in_dashboard: true }
        arguments:
            - ~
            - DesoukOnline\MallBundle\Entity\Category
            - ~


    desouk_online.mall.product:
        class: DesoukOnline\MallBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Mall", label: "Products" , show_in_dashboard: true }
        arguments:
            - ~
            - DesoukOnline\MallBundle\Entity\Product
            - ~


    desouk_online.mall.vendor.product.category:
        class: DesoukOnline\MallBundle\Admin\VendorProductCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Mall", label: "Product categories" , show_in_dashboard: true }
        arguments:
            - ~
            - DesoukOnline\MallBundle\Entity\VendorProductCategory
            - ~

    desouk_online.mall.vendor.article:
        class: DesoukOnline\MallBundle\Admin\ArticleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Mall", label: "Articles" , show_in_dashboard: true }
        arguments:
            - ~
            - DesoukOnline\MallBundle\Entity\Article
            - ~
    
    desouk_online.mall.vendor.image:
        class: DesoukOnline\MallBundle\Admin\VendorImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "DesoukOnline", label: "Images" }
        arguments:
            - ~
            - DesoukOnline\MallBundle\Entity\VendorImage
            - ~
    
    desouk_online.mall.product.image:
        class: DesoukOnline\MallBundle\Admin\ProductImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "DesoukOnline", label: "Product Images" }
        arguments:
            - ~
            - DesoukOnline\MallBundle\Entity\ProductImage
            - ~
            

    